#!/bin/bash

alias sudo='sudo '
# eza
alias l='eza --icons=auto'
alias la='eza -a --icons=auto'
alias ll='eza -l --total-size --icons=auto --git'
alias lla='eza -la --total-size --icons=auto --git'

alias mv='mv -i'
alias cp='cp -i'

# Edit
alias v='nvim'
